In [8]:
1/3

0.3333333333333333

# test

In [9]:
1+2

3

In [14]:
import keras

In [16]:
keras.__version__

'2.1.4'

In [17]:
type(100)

int

In [24]:
print('weight = {0:3.2f} height = {1:3.1f}'.format(100.1234, 200.4567))

weight = 100.12 height = 200.5


In [29]:
z = list(range(10))
print(z)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [30]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [31]:
import numpy as np

In [35]:
x = np.array([1,2,3])
x
print(x)

[1 2 3]


In [36]:
y = np.array([4,5,6])

In [37]:
print(x+y)

[5 7 9]


In [40]:
print(np.arange(5,10))

[5 6 7 8 9]


In [47]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [48]:
x.shape

(2, 3)

In [50]:
np.random.rand(2,3)

array([[0.12304672, 0.90990227, 0.0870366 ],
       [0.72680299, 0.21730659, 0.60200712]])